version: '3.9'

services:
  vscodium:
    container_name: vscodium
    image: lscr.io/linuxserver/vscodium:latest
    cap_add:
      - IPC_LOCK
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuching
    volumes:
      - /data/vscodium/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped